package abi.sbs.doc.financial.gadocumentservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-710022-redhat-00001
 * 2019-08-13T04:17:25.972-07:00
 * Generated source version: 3.1.11.fuse-710022-redhat-00001
 * 
 */
@WebServiceClient(name = "GADocumentServices", 
                  wsdlLocation = "file:/C:/Users/sharath.chaluvegowda/workspace_N/SbsPRCServer/src/main/resources/wsdl/abi/sbs/doc/financial/APDocumentServices/GADocumentServices.wsdl",
                  targetNamespace = "http://abi/sbs/doc/financial/GADocumentServices") 
public class GADocumentServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://abi/sbs/doc/financial/GADocumentServices", "GADocumentServices");
    public final static QName GADocumentServicesSOAP = new QName("http://abi/sbs/doc/financial/GADocumentServices", "GADocumentServicesSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/sharath.chaluvegowda/workspace_N/SbsPRCServer/src/main/resources/wsdl/abi/sbs/doc/financial/APDocumentServices/GADocumentServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GADocumentServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/sharath.chaluvegowda/workspace_N/SbsPRCServer/src/main/resources/wsdl/abi/sbs/doc/financial/APDocumentServices/GADocumentServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GADocumentServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GADocumentServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GADocumentServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GADocumentServices_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GADocumentServices_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GADocumentServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GADocumentServices
     */
    @WebEndpoint(name = "GADocumentServicesSOAP")
    public GADocumentServices getGADocumentServicesSOAP() {
        return super.getPort(GADocumentServicesSOAP, GADocumentServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GADocumentServices
     */
    @WebEndpoint(name = "GADocumentServicesSOAP")
    public GADocumentServices getGADocumentServicesSOAP(WebServiceFeature... features) {
        return super.getPort(GADocumentServicesSOAP, GADocumentServices.class, features);
    }

}
